// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz3VrvfgQ0j9Fa4rmQgbJWc7kulJCpoTk',
    appId: '1:856021985783:web:c8476093432671757626f2',
    messagingSenderId: '856021985783',
    projectId: 'fir-upload-profile-image',
    authDomain: 'fir-upload-profile-image.firebaseapp.com',
    storageBucket: 'fir-upload-profile-image.appspot.com',
    measurementId: 'G-KL58E8P7WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnVBqsEEgfernP6GCsUR5WjN-PQCd3lNg',
    appId: '1:856021985783:android:74b86f248fa7f8327626f2',
    messagingSenderId: '856021985783',
    projectId: 'fir-upload-profile-image',
    storageBucket: 'fir-upload-profile-image.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwMPkSbFPLbCQXOoZKIpdj0ItBpNuGWPI',
    appId: '1:856021985783:ios:a3ea782d109a46fb7626f2',
    messagingSenderId: '856021985783',
    projectId: 'fir-upload-profile-image',
    storageBucket: 'fir-upload-profile-image.appspot.com',
    iosClientId: '856021985783-1dqbl0mn8df76bmjcmdnh73cqld72he6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseUploadProfileImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwMPkSbFPLbCQXOoZKIpdj0ItBpNuGWPI',
    appId: '1:856021985783:ios:a3ea782d109a46fb7626f2',
    messagingSenderId: '856021985783',
    projectId: 'fir-upload-profile-image',
    storageBucket: 'fir-upload-profile-image.appspot.com',
    iosClientId: '856021985783-1dqbl0mn8df76bmjcmdnh73cqld72he6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseUploadProfileImage',
  );
}
